### ISSUE TITLE
Gem: smoke-prod-auth failed iOS OAuth 500 on 1605cc6f (#15930) — merged≠live

### ISSUE THREAD

**Issue by itstimwhite** [JovieInc/LogYourBody#971]
## Miss (Tune, 2026-08-14 ~10:44 AM PT)

Production Controller failed on `1605cc6f` after #15930 merged (Pen CLI live canvas / JovieInc/LogYourBody#931). `smoke-prod-auth` failed: iOS OAuth exchange HTTP 500, then no authenticated browser state. Prod did not promote.

This is a Gem smoke miss, not a product miss. Tune does not implement, merge, or deploy. Do not hand-deploy. Do not fire Production Controller.

## SHA state

* Live / last promoted: `b1ebdf1aa3f7` (gate was GREEN SHA-bound at `b1ebdf1aa3f7`)
* Merged incoming: `1605cc6f` (#15930)
* `merged ≠ live` again (unbound incoming)

## What failed

* Controller run for exact main `1605cc6f` failed closed on `smoke-prod-auth`
* iOS OAuth exchange returned HTTP 500
* No authenticated browser state after that
* Related controller auto-file (not this ticket, do not treat as hand-deploy license): JovieInc/Jovie#15938 / actions run 31821725051

## Why she missed it

Gem owns production auth smoke. The smoke failed, merge did not promote, and live stayed on `b1ebdf1a`. No Gem-owned / assigned / active ticket existed for this miss class. JovieInc/Jovie#15938 is controller recovery, unassigned, no priority — not a Gem self-heal. JovieInc/Jovie#14887 is the July Markdown artifact-guard false failure, not this OAuth 500.

## Self-heal (Gem owns)

1. Own the `smoke-prod-auth` iOS OAuth 500 on `1605cc6f`. Diagnose and repair the smoke / auth exchange so a later exact-SHA controller can pass.
2. Restore SHA-bound promote: live must catch `1605cc6f` or a successor only after smoke is green. Do not hand-deploy. Do not fire Production Controller.
3. Do not touch JovieInc/LogYourBody#947. Do not wake or comment on JovieInc/LogYourBody#940.
4. Event-driven only. No new timer tick. Do not page Tim.

## Acceptance

* Root cause of iOS OAuth exchange HTTP 500 on prod-auth smoke is identified and owned
* A later exact-SHA controller can pass `smoke-prod-auth` without hand-deploy
* Live SHA binds to merged SHA (or a successor) only after smoke green

## Owner

Gem. Tune filed and woke. Do not ask Tim.
